[package]
description = "Rust ADB (Android Debug Bridge) client library"
edition = "2021"
keywords = ["adb", "android"]
license = "MIT"
name = "adb_client"
readme = "README.md"
repository = "https://github.com/cocool97/adb_client"
version = "1.0.3"

[lib]
name = "adb_client"
path = "src/lib.rs"

[[example]]
name = "adb_cli"
path = "examples/adb_cli.rs"

[dependencies]
byteorder = { version = "1.5.0" }
chrono = { version = "0.4.38" }
image = { version = "0.25.1" }
lazy_static = { version = "1.5.0" }
mio = { version = "1.0.0", features = ["os-ext", "os-poll"] }
regex = { version = "1.10.5", features = ["perf", "std", "unicode"] }
thiserror = { version = "1.0.62" }
termios = { version = "0.3.3", optional = true }

## Binary-only dependencies
## Marked as optional so that lib users do not depend on them
[dev-dependencies]
anyhow = { version = "1.0.86" }
clap = { version = "4.5.9", features = ["derive"] }
rand = { version = "0.8.5" }

[target.'cfg(not(windows))'.features]
# termios only supports POSIX platforms, so we exclude it from the windows target
default = ["termios"]
termios = ["termios"]
[target.'cfg(windows)'.features]
deafult = []
termios = ["termios"]
