[package]
name = "adb_client"
version = "0.3.1"
description = "Rust ADB (Android Debug Bridge) client library"
keywords = ["adb", "android"]
readme = "README.md"
license = "MIT"
edition = "2021"
repository = "https://github.com/cocool97/adb_client"

[dependencies]
thiserror = { version = "1.0.31", default_features = false }
regex = { version = "1.5.5", default_features = false, features = ["std", "perf", "unicode"] }
termios = { version = "0.3.3", default_features = false }