[package]
name = "adb_cli"
version = "0.0.1"
description = "Rust ADB (Android Debug Bridge) CLI"
keywords = ["adb", "android"]
readme = "README.md"
license = "MIT"
edition = "2021"
repository = "https://github.com/cocool97/adb_client"


[[bin]]
name = "adb_cli"
test = false
publish = false

[dependencies]
adb_client = { version = "0.3.1", path = "../adb_client" }
anyhow = { version = "1.0.56", default_features = false, features = ["std"] }
clap = { version = "3.1.8", default_features = false, features = ["std", "derive"] }